// Regenerate src/scenes/cislunar/land.ts: the coastlines the Earth and Moon view draws on its spinning globe, from
// Natural Earth's 1:110m land polygons (public domain, https://www.naturalearthdata.com), simplified.
//
//   node scripts/cislunar-land.mjs [path/to/ne_110m_land.geojson]
//
// Without a path it downloads the file. Rings are simplified (Douglas-Peucker, TOLERANCE degrees), small islands and
// Antarctica (never in sight from above the north side of the ecliptic) are dropped, and coordinates are stored in
// tenths of a degree.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const TOLERANCE = 0.45;
/** Smallest ring kept, square degrees (Jamaica is ~1, Taiwan ~3.3). */
const MIN_AREA = 1.6;

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const src = process.argv[2];
const json = src ? JSON.parse(fs.readFileSync(src, 'utf8')) : await (await fetch(URL)).json();

const area = ring => {
  let a = 0;
  for (let i = 0; i < ring.length; i++) {
    const [x0, y0] = ring[i], [x1, y1] = ring[(i + 1) % ring.length];
    a += x0 * y1 - x1 * y0;
  }
  return Math.abs(a) / 2;
};

function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b], dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1;
    let far = -1, dist = tol;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i], d = Math.abs(dy * (px - ax) - dx * (py - ay)) / len;
      if (d > dist) { dist = d; far = i; }
    }
    if (far >= 0) {
      keep[far] = 1;
      stack.push([a, far], [far, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

const rings = [];
for (const f of json.features) {
  const g = f.geometry, polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  for (const poly of polys) {
    const outer = poly[0];
    if (Math.max(...outer.map(p => p[1])) < -55 || area(outer) < MIN_AREA) continue;
    // split the closed ring at its far end so the simplifier keeps both halves' shape
    const open = outer.slice(0, -1), mid = Math.floor(open.length / 2);
    const s = [...simplify(open.slice(0, mid + 1), TOLERANCE).slice(0, -1), ...simplify(open.slice(mid), TOLERANCE)];
    if (s.length >= 4) rings.push(s.flatMap(([x, y]) => [Math.round(x * 10), Math.round(y * 10)]));
  }
}
rings.sort((a, b) => b.length - a.length);
const points = rings.reduce((n, r) => n + r.length / 2, 0);
const body = rings.map(r => `  [${r.join(',')}],`).join('\n');
const out = `/**
 * Coastlines for the Earth and Moon view's globe: Natural Earth 1:110m land (public domain,
 * https://www.naturalearthdata.com), simplified to ~${TOLERANCE} degrees, islands under ~${MIN_AREA} square degrees and
 * Antarctica dropped. Each ring is flat [lon, lat, lon, lat, ...] in tenths of a degree, east and north positive.
 * Generated by \`node scripts/cislunar-land.mjs\`: ${rings.length} rings, ${points} points. Do not edit by hand.
 */
export const LAND: readonly (readonly number[])[] = [
${body}
];
`;
fs.writeFileSync(path.join(root, 'src/scenes/cislunar/land.ts'), out);
console.log(`${rings.length} rings, ${points} points`);
